name: Cache an ubuntu dependency like valgrind

on:
  push:
    paths: ['.github/workflows/cache_deps_ubuntu.yml']
    branches: ['master']
  pull_request:
    paths: ['.github/workflows/cache_deps_ubuntu.yml']
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache valgrind
        uses: actions/cache@v1.0.3
        id: cache-valgrind
        with:
          path: "~/valgrind"
          key: ${{secrets.VALGRIND_VERSION}}
      - name: Install valgrind
        env:
          CACHE_EXISTS: "${{steps.cache-valgrind.outputs.cache-hit}}"
          VALGRIND_VERSION: "${{secrets.VALGRIND_VERSION}}"
        run: |
            if [[ "$CACHE_EXISTS" == 'true' ]]; then
              echo "Using Cached version..."
              sudo cp --verbose --force --recursive ~/valgrind/* /
            else
              echo "Install from repos..."
              sudo apt-get install --yes valgrind="$VALGRIND_VERSION"
              mkdir -p ~/valgrind
              sudo dpkg -L valgrind | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/valgrind/
            fi
      - name: Use Valgrind
        run: valgrind --version --verbose
