name: Cache an ubuntu dependency like valgrind

on:
  push:
    paths: ['.github/workflows/cache_deps_ubuntu.yml']
    branches: ['master']
  pull_request:
    paths: ['.github/workflows/cache_deps_ubuntu.yml']
    branches: ['master']

jobs:
  build:
    env:
      VALGRIND_HOME: "$HOME/valgrind"
      VALGRIND_LIB: "$HOME/valgrind/lib" #https://www.linuxquestions.org/questions/linux-software-2/error-installing-valgrind-failed-to-start-tool-%27memcheck%27-850429/#post4193691
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Cache valgrind
        uses: actions/cache@v1.0.3
        id: cache-valgrind
        with:
          path: "${{env.VALGRIND_HOME}}"
          key: ${{secrets.VALGRIND_VERSION}}
      - name: Install Valgrind
        env:
          CACHE_EXISTS: "${{steps.cache-valgrind.outputs.cache-hit}}"
          VALGRIND_SOURCE: "https://sourceware.org/ftp/valgrind/valgrind-${{secrets.VALGRIND_VERSION}}.tar.bz2"
        run: |
            if [[ "$CACHE_EXISTS" == 'true' ]]; then
              echo "Using Cached version..."
            else
              echo "Install from source..."
              sudo apt-get update
              curl -sSL "$VALGRIND_SOURCE" -o - | tar -xjv --one-top-level=valgrind --strip-components=1
              cd valgrind
              ./configure --prefix="$VALGRIND_HOME"
              make -j
              make install
            fi
            echo "::add-path::$VALGRIND_HOME/bin"
      - name: Install Other Deps
        run: |
         sudo apt-get install --yes libc6-dbg
      - name: Use Valgrind
        run: |
          gcc .github/leaky_main.c
          valgrind --version --verbose
          valgrind --leak-check=full --show-leak-kinds=all ./a.out
