name: Cache an ubuntu dependency like valgrind

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache valgrind
        uses: actions/cache@v1.0.3
        with:
          id: cache-valgrind
          path: "~/valgrind"
          key: ${{secrets.VALGRIND_VERSION}}
      - name: Install valgrind
        env:
          CACHE_HIT: "${{steps.cache-valgrind.outputs.cache-hit}}"
          VALGRIND_VERSION: "${{secrets.VALGRIND_VERSION}}"
        run: |
            echo "$CACHE_HIT"
            if [[ "$CACHE_HIT" == 'true' ]]; then
              echo "Using Cached version..."
              sudo cp --verbose --force --recursive ~/valgrind/* /
            else
              echo "Install from repos..."
              sudo apt install --yes valgrind="$VALGRIND_VERSION"
              mkdir -p ~/valgrind
              sudo dpkg -L valgrind | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/valgrind/
            fi
      - name: Use Valgrind
        run: valgrind --version --verbose
