name: Run a Matrix With Secrets

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      token: ${{secrets[matrix.token]}}
    if: contains(github.event.issue.title, 'matrix_with_secrets')
    strategy:
      matrix:
        token: [token1, token2]
    steps:
    - name: Check matrix token1
      if: startsWith(env.token, 'token1-')
      run: echo 'Token1 is present'
    - name: Check matrix token2
      if: startsWith(env.token, 'token2-')
      run: echo 'Token2 is present'
    - name: Close the issue that started this workflow
      if: startsWith(env.token, 'token2-') # Only second job can close the issue
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: >
          github.issues.update({
            ...context.issue, state: 'closed'
          })
