name: Get outputs from previous step

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'outputs_from_step')
    steps:
    - name: Example Tests
      run: |
           echo "::set-output name=Integration-Tests::2 Integration Tests Failed!\n"
           echo "::set-output name=Unit-Tests::All Unit Tests Passed!\n"
      id: run_tests
    - name: Gather Outputs Of Tests
      run: |
        echo All the outputs:
        echo "${{join(steps.run_tests.outputs.*, '\n')}}"
    - name: Close the issue that started this workflow
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: >
          github.issues.update({
            ...context.issue, state: 'closed'
          })
