name: Use an environment variable in format

# https://stackoverflow.com/questions/59809764/how-to-reference-context-values-in-github-actions-expression-syntax

on:
  push:
    paths: ['.github/workflows/ref-env.yml']
    branches: ['master']
  pull_request:
    paths: ['.github/workflows/ref-env.yml']
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "MYVAR=${{ format('{0}:{1}', env.PATH, env.HOME) }}" | tee --append "$GITHUB_ENV"
      - name: Check environment
        run: echo $MYVAR
