name: Use an environment variable in format

# https://stackoverflow.com/questions/59809764/how-to-reference-context-values-in-github-actions-expression-syntax

on:
  push:
    paths: ['.github/workflows/ref-env.yml']
    branches: ['master']
  pull_request:
    paths: ['.github/workflows/ref-env.yml']
    branches: ['master']

jobs:
  env-from-shell:
    runs-on: ubuntu-latest
    steps:
      - run: printf "MYVAR=${PATH}:${HOME}" | tee --append "$GITHUB_ENV"
      - name: Check environment
        run: echo ${{env.MYVAR}}

  env-dump-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(env) }}
